packages:
  - fixtures/*
  - libs/*

catalog:
  typescript: "6.0.2"
  rolldown: "1.0.2"
  "@types/node": "24.10.1"

overrides:
  vite: "npm:@voidzero-dev/vite-plus-core@0.1.16"
  vitest: "npm:@voidzero-dev/vite-plus-test@0.1.16"
