import type { RouteManifest, RouteManifestRoute } from "./route-manifest.ts";

export const routeTypesEnvPath = "resumable-env.d.ts";
export const routeTypesOutputPath = ".resumable/types/routes.d.ts";
export const routeTypesEnvDeclaration =
  '/// <reference path="./.resumable/types/routes.d.ts" />\n';

export function createRouteTypesDeclaration(manifest: RouteManifest) {
  const routes = manifest.routes;
  const staticHrefs = routes
    .filter((route) => route.params.length === 0)
    .map((route) => stringLiteral(route.pathname));
  const routePatterns = routes
    .filter((route) => route.params.length > 0)
    .map((route) => stringLiteral(route.pattern));

  return [
    "/* This file is generated by Resumable. Do not edit. */",
    'import type { QwikHTMLElements } from "@qwik.dev/core";',
    "",
    createUnion("ResumableStaticPageHref", staticHrefs),
    "",
    createUnion(
      "ResumableConcretePageHref",
      routes.map((route) => hrefType(route))
    ),
    "",
    createUnion("ResumableRoutePattern", routePatterns),
    "",
    createRouteParamsInterface(routes),
    "",
    createUnion("ResumableExternalHref", [
      "`http://${string}`",
      "`https://${string}`",
      "`mailto:${string}`",
      "`tel:${string}`",
      "`#${string}`",
      "`?${string}`"
    ]),
    "",
    "export type ResumableAssetHref = `/${string}.${string}`;",
    "",
    createAnchorTypes(),
    ""
  ].join("\n");
}

function createUnion(name: string, members: readonly string[]) {
  if (members.length === 0) {
    return `export type ${name} = never;`;
  }

  return [
    `export type ${name} =`,
    ...members.map(
      (member, index) => `  | ${member}${index === members.length - 1 ? ";" : ""}`
    )
  ].join("\n");
}

function createRouteParamsInterface(routes: readonly RouteManifestRoute[]) {
  const dynamicRoutes = routes.filter((route) => route.params.length > 0);
  if (dynamicRoutes.length === 0) {
    return "export interface ResumableRouteParams {}";
  }

  return [
    "export interface ResumableRouteParams {",
    ...dynamicRoutes.flatMap((route) => [
      `  ${stringLiteral(route.pattern)}: {`,
      ...route.params.map(
        (param) => `    readonly ${param.name}: ${paramType(param.kind)};`
      ),
      "  };"
    ]),
    "}"
  ].join("\n");
}

function hrefType(route: RouteManifestRoute) {
  if (route.params.length === 0) {
    return stringLiteral(route.pathname);
  }

  return templateLiteralHref(route.pathname);
}

function templateLiteralHref(pathname: string) {
  const segments = splitPathname(pathname).map((segment) => {
    if (segment === "**" || segment.startsWith(":")) {
      return "${string}";
    }

    return segment;
  });

  return `\`/${segments.join("/")}\``;
}

function splitPathname(pathname: string) {
  return pathname === "/" ? [] : pathname.slice(1).split("/");
}

function paramType(kind: RouteManifestRoute["params"][number]["kind"]) {
  return kind === "catch-all"
    ? "string | number | readonly (string | number)[]"
    : "string | number";
}

function stringLiteral(value: string) {
  return JSON.stringify(value);
}

function createAnchorTypes() {
  return [
    'type ResumableBaseAnchorProps = Omit<QwikHTMLElements["a"], "href" | "params">;',
    "",
    "type ResumableRoutePatternAnchorProps = {",
    "  [Pattern in ResumableRoutePattern]: {",
    "    readonly href: Pattern;",
    "    readonly params: ResumableRouteParams[Pattern];",
    "  };",
    "}[ResumableRoutePattern];",
    "",
    "type ResumableConcreteAnchorProps = {",
    "  readonly href?: ResumableStaticPageHref | ResumableExternalHref | ResumableAssetHref;",
    "  readonly params?: never;",
    "};",
    "",
    "export type ResumableAnchorProps = ResumableBaseAnchorProps &",
    "  (ResumableConcreteAnchorProps | ResumableRoutePatternAnchorProps);",
    "",
    "export type ResumableLinkProps = ResumableAnchorProps & {",
    '  readonly prefetch?: boolean | "intent" | "viewport";',
    "  readonly replace?: boolean;",
    "  readonly scroll?: boolean;",
    "};",
    "",
    'declare module "@qwik.dev/core" {',
    "  interface QwikIntrinsicElements {",
    "    a: ResumableAnchorProps;",
    "  }",
    "",
    "  namespace QwikJSX {",
    "    interface IntrinsicElements {",
    "      a: ResumableAnchorProps;",
    "    }",
    "  }",
    "}",
    "",
    'declare module "@resumable.dev/core" {',
    "  interface ResumableGeneratedRoutes {",
    "    readonly anchor: ResumableAnchorProps;",
    "    readonly link: ResumableLinkProps;",
    "  }",
    "}"
  ].join("\n");
}
